NOT FINISHED: Contributing information and application
AndreasTar/Image_2_ASCII pull request #1
Opened 2024-08-06 19:00 UTC by EvilGiraffes

This pull request adds the contributing file and changes the current one to fit

2024-08-07 08:59 UTC, AndreasTar requested changes

2024-08-07 08:59 UTC, AndreasTar commented on src/tools.py
> +def pFormatForSVG(char: str) -> str | None:
this is wrong. The original function returns the input character if it is not inside the SVG_MAPS list, whereas this version would return None, making the `converters.ConvertToSVG()` output wrong results in line 42 of the file src/converters.py. This function should never return none.

2024-08-07 08:59 UTC, AndreasTar commented on CONTRIBUTING.md
> +2. src/readme under TODOs
Also add the various small TODOs and FIXMEs etc scattered throughout the codebase.

2024-08-07 10:36 UTC, EvilGiraffes commented on CONTRIBUTING.md
> +| **Private Class Methods** | pmathodName   |
rah typo forgot and forgot to uppercase

2024-08-07 10:36 UTC, EvilGiraffes commented on CONTRIBUTING.md
> +| **Private Class Fields**  | pfieldName    |
also forgot to uppercase here

2024-08-07 10:36 UTC, EvilGiraffes commented on src/tools.py
> +def pFormatForSVG(char: str) -> str | None:
the original function would return None as it was, but i will change it to ensure it returns char back as a default
Edit: i was wrong

2024-08-09 09:35 UTC, AndreasTar approved these changes

2024-08-09 09:42 UTC, EvilGiraffes commented on src/frontend.py
> +    exit(1)
should have an exit code set when the if condition is true

2024-08-09 21:31 UTC, EvilGiraffes commented
I have made quite a change to the main readme now, hopefully this is okay

2024-08-10 16:20 UTC, AndreasTar commented on README.md
> +or wish to install it on your root environmen you can skip this section**.
typo

2024-08-10 16:38 UTC, AndreasTar approved these changes

2024-08-11 08:14 UTC, AndreasTar approved these changes

2024-08-11 08:14 UTC, merged